// <auto-generated />
using System;
using ASSIGNMENTENTITY.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ASSIGNMENTENTITY.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20200214111145_initial4")]
    partial class initial4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ASSIGNMENTENTITY.Models.Item", b =>
                {
                    b.Property<int>("ItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<int?>("Itemprice")
                        .HasColumnType("int");

                    b.HasKey("ItemID");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("ASSIGNMENTENTITY.Models.Orders", b =>
                {
                    b.Property<string>("Ordersid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ItemID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Ordersdate")
                        .IsRequired()
                        .HasColumnType("Date")
                        .HasMaxLength(30);

                    b.Property<DateTime?>("deliverydate")
                        .HasColumnType("datetime2");

                    b.HasKey("Ordersid");

                    b.HasIndex("ItemID");

                    b.ToTable("order");
                });

            modelBuilder.Entity("ASSIGNMENTENTITY.Models.Orders", b =>
                {
                    b.HasOne("ASSIGNMENTENTITY.Models.Item", "Item")
                        .WithMany("Orders")
                        .HasForeignKey("ItemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
